--TABELA CLIENTES

CREATE TABLE CLIENTE (
	ID INT8 NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	DHCADASTRO TIMESTAMP NULL,
	NOME VARCHAR(150) NOT NULL,
	CONSTRAINT CLIENTE_PKEY PRIMARY KEY (ID)
);

--TABELA SERVICOS

CREATE TABLE SERVICO (
	ID INT8 NOT NULL,
	DESCRICAO VARCHAR(250) NOT NULL,
	VALOR NUMERIC(19, 2) NULL,
	ID_CLIENTE INT8 NULL,
	CONSTRAINT SERVICO_PKEY PRIMARY KEY (ID)
);


-- PUBLIC.SERVICO FOREIGN KEYS

ALTER TABLE PUBLIC.SERVICO ADD CONSTRAINT FKRRKF0PEIY5SR4GKXQDIX59DTW FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID);